GET http://localhost:3000/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc0FkbWluIjpmYWxzZSwiX2lkIjoiNWZiM2YxOTA2MjA0N2Q3ZDc5ODQ5NDA0IiwidXNlcm5hbWUiOiJwYXVsZXR0ZSIsImVtYWlsIjoicGF1bGV0dGVAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkSzU5Sk16MG1MYVMyZXpuTW1wVFg1T2QweGtaY0s5bEFaU1ljTlZ1MHp4UVVBem9KQnc0M1ciLCJpYXQiOjE2MDU3MzQxNzh9.z15xupR2T9m3yDafE7JRR6CiuL9ZPrXwC0v2UgJX3iI

###

POST http://localhost:3000/index
Content-Type: application/json

{
  "email": "paulette@gmail.com",
  "password": "gamer"
}

###

POST http://localhost:3000/inscription
Content-Type: application/json

{
    "username":"tabarnak",
    "email": "tabarnak@gmail.com",
    "password":"gamer",
    "confPwd":"gamer"
}